const tintColorLight = "#ff4c6d";
const tintColorDark = "#ff4c6d";

export default {
  light: {
    text: "#000",
    background: "#fff",
    quoteBackground: "#f7f7f7",
    replyBackground: "#fafafa",
    tabIconDefault: "#ccc",
    border: "#eee",
    inactive: "#ccc",
    highlight: "#ff7096",
    highlightBackground: "#fff",
    button: tintColorLight,
    active: tintColorLight,
    tabIconSelected: tintColorLight,
    tabInactive: "#8e8e8e",
    tint: tintColorLight,
    tintBackground: "#fff",
    overlay: "rgba(255, 255, 255, 0.95)",
    quoteReference: "#eee",
    card: "#fff",
    cardText: "#1c1c1e",
    cardActive: tintColorLight,
    cardInactive: "#ccc",
  },
  dark: {
    text: "#fff",
    background: "#000",
    quoteBackground: "#202124",
    replyBackground: "#1c1c1c",
    tabIconDefault: "#ccc",
    border: "#333",
    inactive: "#444",
    highlight: "#ff7096",
    highlightBackground: "#000",
    tintBackground: "#000",
    button: tintColorDark,
    active: tintColorDark,
    tabIconSelected: tintColorDark,
    tabInactive: "#7c7c7c",
    tint: tintColorDark,
    overlay: "rgba(0, 0, 0, 0.95)",
    quoteReference: "#eee",
    card: "#121212",
    cardText: "#e5e5e7",
    cardActive: tintColorDark,
    cardInactive: "#444",
  },
};
