const tintColorLight = "#ff7096";
const tintColorDark = "#ff7096";

export default {
  light: {
    text: "#000",
    background: "#fff",
    quoteBackground: "#f7f7f7",
    replyBackground: "#fafafa",
    tabIconDefault: "#ccc",
    border: "#eee",
    inactive: "#ccc",
    highlight: "#ff4d6d",
    highlightBackground: "#fff",
    button: tintColorLight,
    active: tintColorLight,
    tabIconSelected: tintColorLight,
    tabInactive: "#8e8e8e",
    tint: tintColorLight,
    tintBackground: "#fff",
    badge: "#ee240e",
    overlay: "rgba(255, 255, 255, 0.95)",
  },
  dark: {
    text: "#fff",
    background: "#000",
    quoteBackground: "#202124",
    replyBackground: "#1c1c1c",
    tabIconDefault: "#ccc",
    border: "#333",
    inactive: "#444",
    highlight: "#ff4d6d",
    highlightBackground: "#000",
    tintBackground: "#000",
    button: tintColorDark,
    active: tintColorDark,
    tabIconSelected: tintColorDark,
    tabInactive: "#7c7c7c",
    tint: tintColorDark,
    badge: "#ee240e",
    overlay: "rgba(0, 0, 0, 0.95)",
  },
};
